//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECard78.Properties
{
  using System;


  /// <summary>
  ///   一个强类型的资源类，用于查找本地化的字符串等。
  /// </summary>
  // 此类是由 StronglyTypedResourceBuilder
  // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
  // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
  // (以 /str 作为命令选项)，或重新生成 VS 项目。
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Resources
  {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources()
    {
    }

    /// <summary>
    ///   返回此类使用的缓存的 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
      get
      {
        if (object.ReferenceEquals(resourceMan, null))
        {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECard78.Properties.Resources", typeof(Resources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   使用此强类型资源类，为所有资源查找
    ///   重写当前线程的 CurrentUICulture 属性。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
      get
      {
        return resourceCulture;
      }
      set
      {
        resourceCulture = value;
      }
    }

    internal static System.Drawing.Bitmap _2_p1
    {
      get
      {
        object obj = ResourceManager.GetObject("2_p1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static string DATA_CHS
    {
      get
      {
        return ResourceManager.GetString("DATA_CHS", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 UPDATE KQ_DayoffType SET DayOffTypeName=&apos;事假&apos; WHERE DayOffTypeNo=&apos;QJ01&apos;
    ///GO
    ///UPDATE KQ_DayoffType SET DayOffTypeName=&apos;病假&apos; WHERE DayOffTypeNo=&apos;QJ02&apos;
    ///GO
    ///UPDATE KQ_DayoffType SET DayOffTypeName=&apos;婚假&apos; WHERE DayOffTypeNo=&apos;QJ03&apos;
    ///GO
    ///UPDATE KQ_DayoffType SET DayOffTypeName=&apos;其他請假&apos; WHERE DayOffTypeNo=&apos;QJ04&apos;
    ///GO
    ///UPDATE KQ_OTType SET OtTypeName=&apos;平時加班&apos; WHERE OtTypeNo=&apos;JB01&apos;
    ///GO
    ///UPDATE KQ_OTType SET OtTypeName=&apos;節日加班&apos; WHERE OtTypeNo=&apos;JB02&apos;
    ///GO
    ///UPDATE KQ_OTType SET OtTypeName=&apos;周末加班&apos; WHERE OtTypeNo=&apos;JB03&apos;
    ///GO
    ///UPDATE K [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string DATA_CHT
    {
      get
      {
        return ResourceManager.GetString("DATA_CHT", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 UPDATE KQ_DayoffType SET DayOffTypeName=&apos;Leave&apos; WHERE DayOffTypeNo=&apos;QJ01&apos;
    ///GO
    ///UPDATE KQ_DayoffType SET DayOffTypeName=&apos;Sick leave&apos; WHERE DayOffTypeNo=&apos;QJ02&apos;
    ///GO
    ///UPDATE KQ_DayoffType SET DayOffTypeName=&apos;Marriage leave&apos; WHERE DayOffTypeNo=&apos;QJ03&apos;
    ///GO
    ///UPDATE KQ_DayoffType SET DayOffTypeName=&apos;Other leave&apos; WHERE DayOffTypeNo=&apos;QJ04&apos;
    ///GO
    ///UPDATE KQ_OTType SET OtTypeName=&apos;Usually Overtime&apos; WHERE OtTypeNo=&apos;JB01&apos;
    ///GO
    ///UPDATE KQ_OTType SET OtTypeName=&apos;Holiday overtime&apos; WHERE OtTypeNo=&apos;JB02&apos;
    ///GO
    ///UPDATE KQ_OTType SET [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string DATA_ENG
    {
      get
      {
        return ResourceManager.GetString("DATA_ENG", resourceCulture);
      }
    }

    internal static System.Drawing.Bitmap DBRefresh
    {
      get
      {
        object obj = ResourceManager.GetObject("DBRefresh", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap Delete
    {
      get
      {
        object obj = ResourceManager.GetObject("Delete", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap EditSelectAll
    {
      get
      {
        object obj = ResourceManager.GetObject("EditSelectAll", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap EditUndo
    {
      get
      {
        object obj = ResourceManager.GetObject("EditUndo", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap EditUnSelectAll
    {
      get
      {
        object obj = ResourceManager.GetObject("EditUnSelectAll", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap Export
    {
      get
      {
        object obj = ResourceManager.GetObject("Export", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap FilePrint
    {
      get
      {
        object obj = ResourceManager.GetObject("FilePrint", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap FilePrintPreview
    {
      get
      {
        object obj = ResourceManager.GetObject("FilePrintPreview", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap FileSave
    {
      get
      {
        object obj = ResourceManager.GetObject("FileSave", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap FileSaveAll
    {
      get
      {
        object obj = ResourceManager.GetObject("FileSaveAll", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap Import
    {
      get
      {
        object obj = ResourceManager.GetObject("Import", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap New
    {
      get
      {
        object obj = ResourceManager.GetObject("New", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap Note
    {
      get
      {
        object obj = ResourceManager.GetObject("Note", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap Search
    {
      get
      {
        object obj = ResourceManager.GetObject("Search", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap SignalLEDBlue
    {
      get
      {
        object obj = ResourceManager.GetObject("SignalLEDBlue", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap SignalLEDGreen
    {
      get
      {
        object obj = ResourceManager.GetObject("SignalLEDGreen", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap SignalLEDLtBlue
    {
      get
      {
        object obj = ResourceManager.GetObject("SignalLEDLtBlue", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap SignalLEDOrange
    {
      get
      {
        object obj = ResourceManager.GetObject("SignalLEDOrange", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap SignalLEDRed
    {
      get
      {
        object obj = ResourceManager.GetObject("SignalLEDRed", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap SignalLEDViolet
    {
      get
      {
        object obj = ResourceManager.GetObject("SignalLEDViolet", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap SignalLEDYellow
    {
      get
      {
        object obj = ResourceManager.GetObject("SignalLEDYellow", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap ToolsHammer
    {
      get
      {
        object obj = ResourceManager.GetObject("ToolsHammer", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   查找类似 IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;DbVersion&apos;)
    ///  CREATE TABLE DbVersion
    ///  (
    ///    DbVersion int NOT NULL,
    ///    DbDate datetime NOT NULL,
    ///    AppVer datetime NULL,
    ///    CONSTRAINT PK_DbVersion PRIMARY KEY(DbVersion)
    ///  )
    ///GO
    ///
    ///IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;SY_Automatism&apos;)
    ///  CREATE TABLE SY_Automatism
    ///  (
    ///    GUID varchar(36) NOT NULL,
    ///    No int NOT NULL,
    ///    AutoTime varchar(5) NULL,
    ///    AutoType int NULL,
    ///    AutoName varchar(255) NULL,
    ///    CONSTRAINT PK_SY_A [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_001
    {
      get
      {
        return ResourceManager.GetString("UPDATE_001", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;RS_CardType&apos;)
    ///  CREATE TABLE RS_CardType
    ///  (
    ///    CardTypeSysID varchar(36) NOT NULL,
    ///    CardTypeID tinyint NOT NULL,
    ///    CardTypeName varchar(50) NULL,
    ///    CardFee money NULL DEFAULT 0,
    ///    CardStored money NULL DEFAULT 0,
    ///    CardDescription varchar(200) NULL,
    ///    CardTypeCredit money NULL,
    ///    CardTypeLC_Monery1 money NULL,
    ///    CardTypeLC_Monery2 money NULL,
    ///    CardTypeLC_Monery3 money NULL,
    ///    CardTypeLC_Monery4 money NULL,
    ///    CardTypeL [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_002
    {
      get
      {
        return ResourceManager.GetString("UPDATE_002", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;KQ_DayoffType&apos;)
    ///  CREATE TABLE KQ_DayoffType
    ///  (
    ///    DayOffTypeSysID varchar(36) NOT NULL,
    ///    DayOffTypeNo varchar(20) NOT NULL,
    ///    DayOffTypeName varchar(50) NOT NULL,
    ///    DayOffIsGS char(1) NULL,
    ///    CONSTRAINT PK_KQ_DayoffType PRIMARY KEY(DayOffTypeSysID)
    ///  )
    ///GO
    ///
    ///IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;KQ_DepShift&apos;)
    ///  CREATE TABLE KQ_DepShift
    ///  (
    ///    GUID varchar(36) NOT NULL,
    ///    DepartSysID varchar(36) NOT NULL,
    ///    DepShif [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_003
    {
      get
      {
        return ResourceManager.GetString("UPDATE_003", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;MJ_Holiday&apos;)
    ///  CREATE TABLE MJ_Holiday
    ///  (
    ///    MJHoliID tinyint NOT NULL,
    ///    MJHoliIsApply bit NULL,
    ///    MJHoliBeginDate datetime NULL,
    ///    MJHoliEndDate datetime NULL,
    ///    MJHoliMemo text NULL,
    ///    CONSTRAINT PK_MJ_Holiday PRIMARY KEY(MJHoliID)
    ///  )
    ///GO
    ///
    ///IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;MJ_MacDoorInfo&apos;)
    ///  CREATE TABLE MJ_MacDoorInfo
    ///  (
    ///    MacSysID varchar(36) NOT NULL,
    ///    MacDoorSysID varchar(36) NOT NULL,
    ///    MacDoorID [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_004
    {
      get
      {
        return ResourceManager.GetString("UPDATE_004", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;SF_Allowance&apos;)
    ///  CREATE TABLE SF_Allowance
    ///  (
    ///    GUID varchar(36) NOT NULL,
    ///    EmpSysID varchar(36) NOT NULL,
    ///    AllowanceFlag datetime NOT NULL,
    ///    AllowanceAmount money NOT NULL,
    ///    AllowanceWay tinyint NOT NULL,
    ///    AllowanceStatus tinyint NOT NULL,
    ///    OprtSysID varchar(36) NOT NULL,
    ///    OprtDate datetime NOT NULL,
    ///    AllowanceAmountUp money NULL,
    ///    AllowanceAmountSum money NULL,
    ///    AllowanceWayUp tinyint NULL,
    ///    CONSTRAINT PK_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_005
    {
      get
      {
        return ResourceManager.GetString("UPDATE_005", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF NOT EXISTS(SELECT * FROM sysobjects WHERE name=&apos;SK_Data&apos;)
    ///  CREATE TABLE SK_Data
    ///  (
    ///    GUID varchar(36) NOT NULL,
    ///    EmpSysID varchar(36) NOT NULL,
    ///    CardNo varchar(10) NULL,
    ///    CardUseTimes int NULL,
    ///    SKType int NULL,
    ///    SKDate datetime NULL,
    ///    SKAmount money NULL,
    ///    SKCardBalance money NULL,
    ///    SKCountHour int NULL,
    ///    OprtSysID varchar(36) NULL,
    ///    OprtDate datetime NULL,
    ///    CONSTRAINT PK_SK_Data PRIMARY KEY(GUID)
    ///  )
    ///GO 的本地化字符串。
    /// </summary>
    internal static string UPDATE_006
    {
      get
      {
        return ResourceManager.GetString("UPDATE_006", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 ALTER TABLE MJ_MacPower ALTER COLUMN CardPhysicsNo varchar(36) NOT NULL
    ///GO
    ///ALTER TABLE MJ_MacPower ADD GUID varchar(36) NULL
    ///GO
    ///UPDATE MJ_MacPower SET GUID=newid() WHERE GUID IS NULL
    ///GO
    ///ALTER TABLE MJ_MacDoorInfo ADD MacDoorPassword varchar(20) NULL
    ///GO
    ///DROP TABLE MJ_MacPassword
    ///GO
    ///ALTER TABLE MJ_MacInfo ADD MacLocks varchar(10)
    ///GO
    ///ALTER TABLE MJ_MacInfo ADD IsReturn char(1)
    ///GO
    ///ALTER TABLE MJ_MacInfo ADD MacReturns varchar(10)
    ///GO
    ///DROP TABLE MJ_MacMoreTool
    ///GO
    ///DROP TABLE MJ_MacMoreCard
    ///GO
    ///A [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_007
    {
      get
      {
        return ResourceManager.GetString("UPDATE_007", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS(SELECT * FROM sysobjects WHERE name=&apos;GetNextDeptList&apos;) DROP FUNCTION GetNextDeptList
    ///GO
    ///CREATE FUNCTION dbo.GetNextDeptList(@ID varchar(50))
    ///  RETURNS varchar(8000) WITH ENCRYPTION AS
    ///BEGIN
    ///  DECLARE @GUID varchar(36),@name varchar(8000),@NID varchar(50),@tmp varchar(8000)
    ///  SELECT @GUID=&apos;&apos;,@name=&apos;&apos;,@NID=&apos;&apos;
    ///  SELECT @GUID=DepartSysId FROM RS_Depart WHERE DepartID=@ID
    ///  DECLARE RecNo CURSOR SCROLL FOR SELECT ISNULL(DepartID,&apos;&apos;) FROM RS_Depart WHERE DepartUpSysID=@GUID
    ///  OPEN RecNo
    ///  FETCH [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_008
    {
      get
      {
        return ResourceManager.GetString("UPDATE_008", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS(SELECT * FROM sysobjects WHERE name=&apos;GetIsNextDayInt&apos;) DROP FUNCTION GetIsNextDayInt
    ///GO
    ///CREATE FUNCTION GetIsNextDayInt(@IntTime int)
    ///  RETURNS int WITH ENCRYPTION AS
    ///BEGIN
    ///  RETURN CASE WHEN @IntTime&lt;0 THEN -1 WHEN @IntTime&gt;86339 THEN 1 ELSE 0 END
    ///END
    ///GO
    ///
    ///IF EXISTS(SELECT * FROM sysobjects WHERE name=&apos;GetIsNextDayStr&apos;) DROP FUNCTION GetIsNextDayStr
    ///GO
    ///CREATE FUNCTION GetIsNextDayStr(@IntTime int)
    ///  RETURNS varchar(1) WITH ENCRYPTION AS
    ///BEGIN
    ///   RETURN CASE WHEN @IntTime&gt;86399 THEN &apos; [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_009
    {
      get
      {
        return ResourceManager.GetString("UPDATE_009", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VRS_EmpSex&apos;) DROP VIEW VRS_EmpSex
    ///GO
    ///CREATE VIEW VRS_EmpSex WITH ENCRYPTION
    ///AS
    ///  SELECT GUID AS EmpSexSysID,ID AS EmpSexID,Name AS EmpSexName
    ///    FROM SY_ID2Name
    ///    WHERE Class=&apos;EmpSex&apos;
    ///GO
    ///
    ///IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VRS_EmpStatus&apos;) DROP VIEW VRS_EmpStatus
    ///GO
    ///CREATE VIEW VRS_EmpStatus WITH ENCRYPTION
    ///AS
    ///  SELECT ID AS EmpStatusID,Name AS EmpStatusName
    ///    FROM SY_ID2Name
    ///    WHERE Class=&apos;EmpStatusID&apos;
    ///GO
    ///
    ///IF EXISTS (SELEC [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_010
    {
      get
      {
        return ResourceManager.GetString("UPDATE_010", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VSY_Oprt&apos;) DROP VIEW VSY_Oprt
    ///GO
    ///CREATE VIEW VSY_Oprt WITH ENCRYPTION
    ///AS
    ///  SELECT CAST(0 AS bit) AS SelectCheck,OprtSysID,OprtNo,OprtName,
    ///    CAST(CASE OprtIsActive WHEN &apos;Y&apos; THEN 1 ELSE 0 END AS bit) AS OprtIsActive,
    ///    OprtLastLoginTime,OprtDesc,OprtStartDay,OprtEndDay,
    ///    CAST(CASE RoleIsSys WHEN &apos;Y&apos; THEN 1 ELSE 0 END AS bit) AS RoleIsSys
    ///    FROM SY_Oprt
    ///GO
    ///
    ///IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VSY_BlackCard&apos;) DROP VIEW VSY_BlackCar [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_011
    {
      get
      {
        return ResourceManager.GetString("UPDATE_011", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VKQ_MacInfo&apos;) DROP VIEW VKQ_MacInfo
    ///GO
    ///CREATE VIEW VKQ_MacInfo WITH ENCRYPTION
    ///AS
    ///  SELECT CAST(0 AS bit) AS SelectCheck,&apos;&apos; AS MacStatus,MacSysID,CAST(MacSN as int) AS MacSN,MacType,
    ///    MacConnType,MacIPAddress,MacPort,MacConnPWD,MacPhysicsAddress,MacDesc,IsBigMac
    ///    FROM KQ_MacInfo
    ///GO
    ///
    ///IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VKQ_OTType&apos;) DROP VIEW VKQ_OTType
    ///GO
    ///CREATE VIEW VKQ_OTType WITH ENCRYPTION
    ///AS
    ///  SELECT CAST(0 AS bit) AS SelectC [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_012
    {
      get
      {
        return ResourceManager.GetString("UPDATE_012", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VMJ_Holiday&apos;) DROP VIEW VMJ_Holiday
    ///GO
    ///CREATE VIEW VMJ_Holiday WITH ENCRYPTION
    ///AS
    ///  SELECT CAST(0 AS bit) AS SelectCheck,*
    ///    FROM MJ_Holiday
    ///GO
    ///
    ///IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VMJ_MacInfo&apos;) DROP VIEW VMJ_MacInfo
    ///GO
    ///CREATE VIEW VMJ_MacInfo WITH ENCRYPTION
    ///AS
    ///  SELECT CAST(0 AS bit) AS SelectCheck,&apos;&apos; AS MacStatus,MacSysID,&apos;0&apos;+CAST(MacDoorType AS varchar(1))+MacSN AS MacSN,
    ///    MacConnType,MacIPAddress,MacPort,MacConnPWD,MacDesc,Se [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_013
    {
      get
      {
        return ResourceManager.GetString("UPDATE_013", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VSF_MacOpter&apos;) DROP VIEW VSF_MacOpter
    ///GO
    ///CREATE VIEW VSF_MacOpter WITH ENCRYPTION
    ///AS
    ///  SELECT CAST(0 AS bit) AS SelectCheck,MacOpterID,MacOpterName,GUID,MacOpterPWD
    ///    FROM SF_MacOpter
    ///GO
    ///
    ///IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VSF_MacProducts&apos;) DROP VIEW VSF_MacProducts
    ///GO
    ///CREATE VIEW VSF_MacProducts WITH ENCRYPTION
    ///AS
    ///  SELECT CAST(0 AS bit) AS SelectCheck,ProductsID,ProductsName,ProductsPrice,GUID
    ///    FROM SF_MacProducts
    ///GO
    ///
    ///IF EXI [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_014
    {
      get
      {
        return ResourceManager.GetString("UPDATE_014", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VSK_SKType&apos;) DROP VIEW VSK_SKType
    ///GO
    ///CREATE VIEW VSK_SKType WITH ENCRYPTION
    ///AS
    ///  SELECT GUID AS SKTypeSysID,ID AS SKTypeID,Name AS SKTypeName
    ///    FROM SY_ID2Name
    ///    WHERE Class=&apos;SKType&apos;
    ///GO
    ///
    ///IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;VSK_Data&apos;) DROP VIEW VSK_Data
    ///GO
    ///CREATE VIEW VSK_Data WITH ENCRYPTION
    ///AS
    ///  SELECT c.EmpSysID,c.EmpNo,c.EmpName,c.CardSectorNo,c.DepartID,c.DepartName,a.GUID,a.CardNo,a.SKType AS SKTypeID,a.SKDate,
    ///    a.SKAmount [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_015
    {
      get
      {
        return ResourceManager.GetString("UPDATE_015", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS(SELECT * FROM sysobjects WHERE name=&apos;PGetMaxIDFromTable&apos;) DROP PROCEDURE PGetMaxIDFromTable
    ///GO
    ///CREATE PROCEDURE PGetMaxIDFromTable(@FieldName varchar(50),@TableName varchar(50)) WITH ENCRYPTION AS
    ///  DECLARE @S varchar(8000)
    ///  SELECT @S=&apos;SELECT ISNULL(MIN(b.&apos;+@FieldName+&apos;),0)+1 AS MaxID FROM(SELECT CAST(a.&apos;+@FieldName+&apos; AS bigint) AS &apos;+@FieldName+&apos; FROM &apos;+@TableName+
    ///    &apos; AS a WHERE ISNUMERIC(a.&apos;+@FieldName+&apos;)=1 AND NOT EXISTS(SELECT 1 FROM &apos;+@TableName+&apos; WHERE ISNUMERIC(&apos;+@FieldName+&apos;)=1 AND [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_016
    {
      get
      {
        return ResourceManager.GetString("UPDATE_016", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;PRS_EmpCardFa&apos;) DROP PROCEDURE PRS_EmpCardFa
    ///GO
    ///CREATE PROCEDURE PRS_EmpCardFa(@EmpSysID varchar(36),@CardSectorNo varchar(10),@CardData10 varchar(10),@CardData8 varchar(8),
    ///  @CardBalance money,@CardUseDate datetime,@CardUseTimes int,@SFAmount money,@DiscountM money,@OprtSysID varchar(36),
    ///  @CardStatusID int,@OpterType int) WITH ENCRYPTION AS
    ///  DECLARE @SFDate datetime,@SFCardFee money,@UseTimes int,@Discount money
    ///  SELECT @SFDate=getdate(),@Discount= [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_017
    {
      get
      {
        return ResourceManager.GetString("UPDATE_017", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;PKQ_KQDataSave&apos;) DROP PROCEDURE PKQ_KQDataSave
    ///GO
    ///CREATE PROCEDURE PKQ_KQDataSave(@CardType tinyint,@CardNo varchar(10),@KQDate datetime,@KQTime int,@DevID smallint,
    ///  @ReaderID tinyint,@PhotoPash varchar(200),@OprtSysID varchar(36),@ReadMark tinyint) WITH ENCRYPTION AS
    ///  DECLARE @EmpSysID varchar(36)
    ///  IF @CardType=0
    ///    SELECT @EmpSysID=EmpSysID FROM RS_EmpCard WHERE CardSectorNo=@CardNo
    ///  ELSE IF @CardType=1
    ///    SELECT @EmpSysID=EmpSysID FROM RS_Emp [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_018
    {
      get
      {
        return ResourceManager.GetString("UPDATE_018", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;PMJ_MJDataSave&apos;) DROP PROCEDURE PMJ_MJDataSave
    ///GO
    ///CREATE PROCEDURE PMJ_MJDataSave(@CardProtocol tinyint,@CardNo varchar(10),@MJDate datetime,@MJTime int,@MacSN varchar(10),
    ///  @ReaderID varchar(10),@OprtSysID varchar(36),@Memo varchar(200),@IsPass char(1)) WITH ENCRYPTION AS
    ///  DECLARE @EmpSysID varchar(36),@MacSysID varchar(36),@MacDoorSysID varchar(36),@MacReadSysID varchar(36),@DoorID varchar(10)
    ///  IF @CardProtocol=0
    ///    SELECT @EmpSysID=EmpSysID FROM R [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_019
    {
      get
      {
        return ResourceManager.GetString("UPDATE_019", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;PSF_SFDataInsertDM&apos;) DROP PROCEDURE PSF_SFDataInsertDM
    ///GO
    ///CREATE PROCEDURE PSF_SFDataInsertDM(@EmpSysID varchar(36),@CardNo varchar(10),@SFType int,@SFDate datetime,@SFAmount money,@CardBalance money,
    ///  @SFMealTypeID int,@SFMacSn varchar(7),@SFOprtNo int,@CardUseTimes int,@OprtSysID varchar(36),@ProductInfo varchar(8000)) WITH ENCRYPTION AS
    ///  DECLARE @i int,@GUID varchar(36),@ProductID int,@ProductNum int,@tmp varchar(7)
    ///  DECLARE @ProductPrice money,@Pro [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_020
    {
      get
      {
        return ResourceManager.GetString("UPDATE_020", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS(SELECT * FROM sysobjects WHERE name=&apos;PSK_SKDataInsert&apos;) DROP PROCEDURE PSK_SKDataInsert
    ///GO
    ///CREATE PROCEDURE PSK_SKDataInsert(@CardNo varchar(10),@SKType int,@SKDate datetime,@SKAmount money,
    ///  @CardBalance money,@OprtSysID varchar(36)) WITH ENCRYPTION AS
    ///  DECLARE @EmpSysID varchar(36)
    ///  SELECT @EmpSysID=EmpSysID FROM Rs_EmpCard WHERE CardSectorNo=@CardNo
    ///  IF @EmpSysID IS NULL SELECT @EmpSysID=&apos;&apos;
    ///  IF LEN(@EmpSysID)&gt;0
    ///    INSERT INTO SK_Data(GUID,EmpSysID,CardNo,SKType,SKDate,SKAmount,SKC [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_021
    {
      get
      {
        return ResourceManager.GetString("UPDATE_021", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;Tr_SY_OprtDelete&apos;) DROP TRIGGER Tr_SY_OprtDelete
    ///GO
    ///CREATE TRIGGER Tr_SY_OprtDelete ON SY_Oprt WITH ENCRYPTION
    ///FOR DELETE
    ///AS 
    ///  DECLARE @OprtSysID varchar(36)
    ///  SELECT @OprtSysID=OprtSysID FROM Deleted
    ///  DELETE FROM SY_OprtPower WHERE OprtSysID=@OprtSysID
    ///GO 的本地化字符串。
    /// </summary>
    internal static string UPDATE_022
    {
      get
      {
        return ResourceManager.GetString("UPDATE_022", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;Tr_RS_EmpInsert&apos;) DROP TRIGGER Tr_RS_EmpInsert
    ///GO
    ///CREATE TRIGGER Tr_RS_EmpInsert ON RS_Emp WITH ENCRYPTION
    ///FOR INSERT
    ///AS 
    ///  DECLARE @EmpSysID varchar(36)
    ///  DECLARE @MaxFingerNo bigint
    ///  DECLARE @MaxCardFingerNo bigint
    ///  SELECT @EmpSysID=EmpSysID FROM Inserted
    ///  --同步人员相片表
    ///  IF NOT EXISTS(SELECT EmpSysID FROM RS_EmpPhoto WHERE EmpSysID=@EmpSysID)
    ///    INSERT INTO RS_EmpPhoto(GUID,EmpSysID) VALUES(newid(),@EmpSysID)
    ///  --同步人员卡片表
    ///  IF NOT  EXISTS(SELECT [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_023
    {
      get
      {
        return ResourceManager.GetString("UPDATE_023", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;Tr_KQ_DayoffTypeINSERT&apos;) DROP TRIGGER Tr_KQ_DayoffTypeINSERT
    ///GO
    ///CREATE TRIGGER Tr_KQ_DayoffTypeINSERT ON KQ_DayoffType WITH ENCRYPTION
    ///FOR INSERT
    ///AS
    ///  IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;PKQ_CreateKQResult&apos;) EXEC PKQ_CreateKQResult
    ///GO
    ///
    ///IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;Tr_KQ_DayoffTypeUPDATE&apos;) DROP TRIGGER Tr_KQ_DayoffTypeUPDATE
    ///GO
    ///CREATE TRIGGER Tr_KQ_DayoffTypeUPDATE ON KQ_DayoffType WITH ENCRYPTION
    ///FOR UPDATE
    ///AS
    ///  IF U [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_024
    {
      get
      {
        return ResourceManager.GetString("UPDATE_024", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;Tr_MJ_MJDataInsert&apos;) DROP TRIGGER Tr_MJ_MJDataInsert
    ///GO
    ///CREATE TRIGGER Tr_MJ_MJDataInsert ON MJ_MJData WITH ENCRYPTION
    ///FOR INSERT
    ///AS 
    ///  DECLARE @GUID varchar(36),@EmpSysID varchar(36),@MacReadSysID varchar(36),@MJDate datetime,@MJTime int
    ///  SELECT @GUID=GUID,@EmpSysID=EmpSysID,@MacReadSysID=MacReadSysID,@MJDate=MJDate,@MJTime=MJTime FROM Inserted
    ///  IF EXISTS(SELECT * FROM MJ_MacReadInfo WHERE MacReadSysID=@MacReadSysID AND IsApplyWork=&apos;Y&apos;) AND
    ///    EXIS [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_025
    {
      get
      {
        return ResourceManager.GetString("UPDATE_025", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 IF EXISTS (SELECT * FROM sysobjects WHERE NAME=&apos;Tr_SF_SFDataINSERT&apos;) DROP TRIGGER Tr_SF_SFDataINSERT
    ///GO
    ///CREATE TRIGGER Tr_SF_SFDataINSERT ON SF_SFData WITH ENCRYPTION
    ///FOR INSERT
    ///AS
    ///  DECLARE @EmpSysID varchar(36),@CardUseTimes int,@SFDate datetime,@SFType int,@SFAmount money,@UseTimes int,@sft datetime
    ///  DECLARE @CardStatusID int,@BTFlag datetime,@MacSN varchar(7)
    ///  SELECT @EmpSysID=EmpSysID,@CardUseTimes=ISNULL(CardUseTimes,0),@SFDate=SFDate,@SFType=SFType,@SFAmount=SFAmount,
    ///    @BTFlag=BTFlag,@Ma [字符串的其余部分被截断]&quot;; 的本地化字符串。
    /// </summary>
    internal static string UPDATE_026
    {
      get
      {
        return ResourceManager.GetString("UPDATE_026", resourceCulture);
      }
    }

    /// <summary>
    ///   查找类似 UPDATE DbVersion SET DbDate=&apos;2014-01-08&apos;
    ///GO
    ///EXEC PKQ_CreateKQResult
    ///GO
    ///EXEC PSF_CreateDepositView
    ///GO 的本地化字符串。
    /// </summary>
    internal static string UPDATE_027
    {
      get
      {
        return ResourceManager.GetString("UPDATE_027", resourceCulture);
      }
    }

    internal static System.Drawing.Bitmap ViewZoomIn
    {
      get
      {
        object obj = ResourceManager.GetObject("ViewZoomIn", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap ViewZoomOut
    {
      get
      {
        object obj = ResourceManager.GetObject("ViewZoomOut", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap T1
    {
      get
      {
        object obj = ResourceManager.GetObject("T1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap T2
    {
      get
      {
        object obj = ResourceManager.GetObject("T2", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap T3
    {
      get
      {
        object obj = ResourceManager.GetObject("T3", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _1_1
    {
      get
      {
        object obj = ResourceManager.GetObject("_1_1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _1_2
    {
      get
      {
        object obj = ResourceManager.GetObject("_1_2", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _1_3
    {
      get
      {
        object obj = ResourceManager.GetObject("_1_3", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _2_1
    {
      get
      {
        object obj = ResourceManager.GetObject("_2_1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _2_2
    {
      get
      {
        object obj = ResourceManager.GetObject("_2_2", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _2_3
    {
      get
      {
        object obj = ResourceManager.GetObject("_2_3", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _3_1
    {
      get
      {
        object obj = ResourceManager.GetObject("_3_1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _3_2
    {
      get
      {
        object obj = ResourceManager.GetObject("_3_2", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _3_3
    {
      get
      {
        object obj = ResourceManager.GetObject("_3_3", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _3_4
    {
      get
      {
        object obj = ResourceManager.GetObject("_3_4", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _3_5
    {
      get
      {
        object obj = ResourceManager.GetObject("_3_5", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _3_6
    {
      get
      {
        object obj = ResourceManager.GetObject("_3_6", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _4_1
    {
      get
      {
        object obj = ResourceManager.GetObject("_4_1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _4_2
    {
      get
      {
        object obj = ResourceManager.GetObject("_4_2", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _4_3
    {
      get
      {
        object obj = ResourceManager.GetObject("_4_3", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _4_4
    {
      get
      {
        object obj = ResourceManager.GetObject("_4_4", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _4_5
    {
      get
      {
        object obj = ResourceManager.GetObject("_4_5", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _4_6
    {
      get
      {
        object obj = ResourceManager.GetObject("_4_6", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _5_1
    {
      get
      {
        object obj = ResourceManager.GetObject("_5_1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _5_2
    {
      get
      {
        object obj = ResourceManager.GetObject("_5_2", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _5_3
    {
      get
      {
        object obj = ResourceManager.GetObject("_5_3", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _5_4
    {
      get
      {
        object obj = ResourceManager.GetObject("_5_4", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _5_5
    {
      get
      {
        object obj = ResourceManager.GetObject("_5_5", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _5_6
    {
      get
      {
        object obj = ResourceManager.GetObject("_5_6", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _6_1
    {
      get
      {
        object obj = ResourceManager.GetObject("_6_1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _6_2
    {
      get
      {
        object obj = ResourceManager.GetObject("_6_2", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap _6_3
    {
      get
      {
        object obj = ResourceManager.GetObject("_6_3", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap button1
    {
      get
      {
        object obj = ResourceManager.GetObject("button1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap button2
    {
      get
      {
        object obj = ResourceManager.GetObject("button2", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap Exit
    {
      get
      {
        object obj = ResourceManager.GetObject("Exit", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap ExitSystem
    {
      get
      {
        object obj = ResourceManager.GetObject("ExitSystem", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap logo
    {
      get
      {
        object obj = ResourceManager.GetObject("logo", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    internal static System.Drawing.Bitmap about
    {
      get
      {
        object obj = ResourceManager.GetObject("about", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
  }
}
