IF EXISTS (SELECT * FROM sysobjects WHERE NAME='TR_SEA_SnapShots') DROP TRIGGER TR_SEA_SnapShots
GO
CREATE TRIGGER TR_SEA_SnapShots ON SEA_SnapShots WITH ENCRYPTION
FOR DELETE
AS
  DECLARE @GUID varchar(36)
  SELECT @GUID=[GUID] FROM deleted
	DELETE FROM SEA_SnapShotsPhoto where [GUID]=@GUID
GO